---
title: Promise
date: 2021-05-17 21:17:57
permalink: /pages/c4e0c3/
categories:
  - 前端乱炖
  - JavaScript
tags:
  - JavaScript
---
### 前言

说到promise的出现，我们先得看看我们为什么会使用回调函数：考虑这样的应用场景，当我们的函数中具有异步操作时，我们如何监听这个异步操作呢？合理的情况是，我们可以同时监听异步操作的成功和失败，并且对异步操作的成功或者失败具有响应能力或者说控制权。但是当我们的异步操作很多，并且要求控制每一个异步操作的执行顺序，就难免会定义很多的回调函数，同时为了控制顺序，也会嵌套回调函数，当回调函数的层级很深的时候，就会产生所谓的回调地狱，而promise的出现正是为了解决这种困境。

### promise的简单介绍

> 正如其意，promise表示承诺的意思。promise可以类比生产者和消费者，生产者对消费者承诺一批商品，消费者通过某种方式和生产者进行连接，并使用之前规定好的方式消费生产者生产的商品。生产者只需要建立这种联系，将商品给到消费者，消费者消费的时候，商品或好或坏，两种结果下消费者会有不同的处理，但是商品的状态是不可逆的，可能是好东西或者是残次品。同时同一个商品不能同时存在两种状态，好东西和残次品应该是互斥的。

首先来看看生产者-promise构造函数

```js
let promise = new Promise (function (resolve, reject) {
  // 这就是生产者生产的商品
})
```

其中，传入`promise构造函数`的函数被称作**executor**，这就是生产者和消费者建立联系的方式，通过向`promise构造函数`中传入`executor`。每一个`executor`都有两个回调的函数，这是JS引擎内置的两个回调函数，不用我们自己定义。

> - resolve(value)  如果任务成功就返回value
> - reject(error)    如果任务执行失败 并且有error，就返回error对象

简单来说，`executor`会执行某个任务，执行时间我们并不关心，任务执行成功我们就调用`resolve`，任务执行失败我们就执行`reject`。

每一个使用`new promise`构造函数返回的对象都具有`executor`属性，方便我们跟踪任务的进行状态:

> - state: 最开始是pending,表示这是在等待状态；当任务执行成功后，调用resolve函数，state会变成fulfilled;任务执行失败后，调用reject函数，state会变成rejected。
> - result: 最开始是undefined,调用resolve(value)的时候变成value, 或者在调用reject(erroe)的时候变成error。

#### 1.正如前面提到的同一个商品只能有一个评价，state的状态也只能是一种

```js
// 这里的宗旨是：只能是resolve或者reject,且只能存在一个。
let promise = new Promise(function(resolve, reject) {
  resolve("done");

  reject(new Error("…")); // 被忽略
  setTimeout(() => resolve("…")); // 被忽略
});
```

如果`executor`出现了什么错误，`executor`会立即调用`reject`函数，传入`reject`的参数可以是任何值，但是推荐使用`Error对象`，能更好的体现`executor`发生了错误。

`resolve`和`reject`可以立即调用。一般来说，都是等待`executor`运行的结果，然后自动调用`resolve`和`reject`这两个回调函数，但是我么也可以显示的调用`resolve`和`reject`

```js
let promise = new Promise(function(resolve, reject) {
  resolve("done");
});
```

再来看消费者是如何消费的

> 消费者接受商品的方式主要是三种：`then`、`catch`、`finally`

#### 2.then

```js
let promise = new Promise(function(resolve, reject) {
    // 当 promise 被构造完成时，自动执行此函数
    setTimeout(() => resolve("这个任务执行成功了！！"), 1000);
  });

  promise.then((result) => {
      console.log(result); // 1秒后 这个任务执行成功了！！
  })
```

消费者可以这样接收质量上乘的商品，但是遇到残次品呢？我们得这样：

```js
let promise = new Promise(function(resolve, reject) {
    // 当 promise 被构造完成时，自动执行此函数
    setTimeout(() => reject(new Error("任务执行失败！！")), 1000);
  });

  promise.then((err) => {
      console.log(err); // Error: 任务执行失败！！
  })
```

`then`方法有两个参数，第一个函数是接收`executor`执行成功后的结果，第二个函数是接收`executor`执行失败后的结果。

```js
let promise = new Promise(function(resolve, reject) {
    // 当 promise 被构造完成时，自动执行此函数
  });

  promise.then((result) => {
      console.log(result);
  },(err) => {
      console.log(err); 
  })
```

#### 3.catch

在上面说到当`state`变为 的时候，可以使用`then(null,rejection)``或then(undefined, rejection)`捕捉错误,但是`promise`给我们提供了更加优雅的捕捉错误的做法，就是使用`catch`,如下面的例子:

```js
let promise = new Promise(function(resolve, reject) {
    // 当 promise 被构造完成时，自动执行此函数
    setTimeout(() => reject(new Error("任务执行失败！！")), 1000);
  });

  promise.catch(console.log) // Error: 任务执行失败！！
```

#### 4.finally

不管executor执行的结果是成功还是失败，总有一些情况是都会处理的，比如清理不用多变量，这个时候就要用到finally:

```js
let promise = new Promise(function(resolve, reject) {
    // 当 promise 被构造完成时，自动执行此函数
    setTimeout(() => reject(new Error("任务执行失败！！")), 1000);
  });

  promise.finally().then(null,(err) => {
      console.log(err);
  })
```

这里finally是将执行的结果进行传递，返回也是一个promise，可以使用then方法进行接收。

### 对promise的简单实现

一个完美的`promise`应该符合[promise A+规范](httpshttps://malcolmyu.github.io/2015/06/12/Promises-A-Plus/#://malcolmyu.github.io/2015/06/12/Promises-A-Plus/#)，该规范详尽描述了promise的各种行为，我们先来实现一个简易版的`promise`，简易版符合下面的要求:

> - 当new MyPromise构造函数执行完毕，立即执行传入的函数executor
> - 自定义的MyPromise类有三种状态，pending、fulfilled、rejected三种状态，初始状态都是pending。executor有两个回调函数参数，resolve和reject；当executor执行时，调用resolve，MyPromise类的state是fulfilled;调用reject，state变为rejected
> - 存在一个then方法，也有两个回调参数，onFulfilled和onRejected;当onFulfilled不是函数时，直接返回onFulfilled的值；当onRejected不是函数时，直接返回原因。当onFulfilled和onRejected都是函数时，若是state时fulfilled时，直接调用onFulfilled；当state是rejected时，直接调用onRejected。

```js
// 简易版promise

// 定义一个函数：判断传入的变量是否是函数
const isFunction = variable => typeof variable === 'function';

// 定义Promise的三种状态: pending、fulfilled、rejected

const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

// 定义一个自己的Promise类
class MyPromise {
    constructor(executor) {
        if (!isFunction(executor)) {
            return new Error("大兄弟，传入的不是函数！！")
        }

        this._state = PENDING; // 初始状态
        this._value = null; //成功返回的值
        this._reason = null; //失败返回的原因

        try {
            // 构造函数执行完成，立即执行executor函数(注意，需要使用bind绑定this的上下文)
            executor(this._resolve.bind(this), this._reject.bind(this))
        } catch (err) {
           this._reject(err)
        }
    }

    // resolve函数
    _resolve (val) {
        if (this._state !== PENDING) return;
        this._state = FULFILLED;
        this._value = val;
    }

    //  reject函数
    _reject (err) {
        if (this._state !== PENDING) return;
        this._state = REJECTED;
        this._reason = err;
    }
}

// 实现then方法
MyPromise.prototype.then = function(onFulfilled, onRejected) {

    let realOnFulfilled = onFulfilled;
    let realOnRejected = onRejected;

    if (!isFunction(realOnFulfilled)) {
        realOnFulfilled = function (value) {
            return value;
        }
    }

    if (!isFunction(realOnRejected)) {
        realOnRejected = function (reason) {
            if (reason instanceof Error) {
                return reason;
            } else {
                throw new Error(reason)
            }
        }
    }

    // promise状态是fulfilled，会立即调用onFulfilled;
    // promise状态是rejected, 会立即调用onRejected;
    if (this._state === FULFILLED) {
        realOnFulfilled(this._value)
    }

    if (this._state === REJECTED) {
        realOnRejected(this._reason)
    }
}

// 测试
let promise = new MyPromise((resolve, reject) => {
   resolve(111)
}).then((res) => {
    console.log(res); // 111
})

let promise = new MyPromise((resolve, reject) => {
    reject("我错了")
}).then(null, (err) => {
    console.log(err); // 我错了
})
```

可以看到，基本实现了最简单的`promise`，在构造函数中`resolve`和`reject`时，我们可以在实例的`then`方法中的第一个参数拿到`promise`实例中`resolve`的值；在第二个参数中拿到`promise`实例中`reject`的原因。

但是参考规范中`then`方法的行为，我们这里的实现是远远达不到标准的,我们将`then`方法的行为罗列下:

#### 1.then方法的两个参数

> - then方法的两个参数onFulfilled和onRejected，如果其值不是函数时，其值必须被忽略

对于onFulfilled的特性(onFulfilled是函数)

> - promise为resolve(state是fulFilled)时调用onFulfilled，onFulfilled的第一个参数为resolve传入的值。
> - 在promise状态改变前不可调用
> - 调用次数不能超过一次

对于onRejected的特性(onRejected是函数)

> - promise为reject(state是rejected)时调用onFulfilled，onRejected的第一个参数为reject传入的值。
> - 在promise状态改变前不可调用
> - 调用次数不能超过一次

#### 2.then方法可以被同一个promise对象调用多次

> - 当 `promise` 成功状态时，所有 `onFulfilled` 需按照其注册顺序依次回调
> - 当 `promise` 失败状态时，所有 `onRejected` 需按照其注册顺序依次回调

#### 3.返回值

> then方法返回一个promise对象

所以`promise`支持链式调用

```js
promise1.then(onFulfilled1, onRejected1).then(onFulfilled2, onRejected2);
```

这里链式调用规范也定义了各种情况下的行为规范,其实主要是**值的传递和错误的捕获机制**:

 如果 `onFulfilled` 或者 `onRejected` 返回一个值 `x` ，则运行下面的 `Promise` 解决过程：`[[Resolve]](promise2, x)`

> - 若 `x` 不为 `Promise` ，则使 `x` 直接作为新返回的 `Promise` 对象的值， 即新的`onFulfilled` 或者 `onRejected` 函数的参数.
> - 若 `x` 为 `Promise` ，这时后一个回调函数，就会等待该 `Promise` 对象(即 `x` )的状态发生变化，才会被调用，并且新的 `Promise` 状态和 `x` 的状态相同。

```js
// 这里就是返回了一个值，所以promise1会将这个值传递给promise2的then方法
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve()
  }, 1000)
})
promise2 = promise1.then(res => {
  // 返回一个普通值
  return '这里返回一个普通值'
})
promise2.then(res => {
  console.log(res) //1秒后打印出：这里返回一个普通值
})
```

再来看这个例子：

```js
// 这里是返回了一个promise,promise2会等待promise1和then方法中的回调函数执行完毕，并且拿到promise1的执行结果作为then方法回调函数的参数
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve()
  }, 1000)
})
promise2 = promise1.then(res => {
  // 返回一个Promise对象
  return new Promise((resolve, reject) => {
    setTimeout(() => {
     resolve('这里返回一个Promise')
    }, 2000)
  })
})
promise2.then(res => {
  console.log(res) //3秒后打印出：这里返回一个Promise
})
```

 如果 `onFulfilled` 或者 `onRejected` 抛出异常`e`,那个promise2的状态必须为`rejected`,并且返回`e`，例如：

```js
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
promise2 = promise1.then(res => {
  throw new Error('这里抛出一个异常e')
})
promise2.then(res => {
  console.log(res)
}, err => {
  console.log(err) //1秒后打印出：这里抛出一个异常e
})
```

如果`onFulfilled` 不是函数且 `promise1` 状态为成功`（Fulfilled）`， `promise2` 必须变为成功`（Fulfilled）`并返回 `promise1` 成功的值，例如：

```js
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
promise2 = promise1.then('这里的onFulfilled本来是一个函数，但现在不是')
promise2.then(res => {
  console.log(res) // 1秒后打印出：success
}, err => {
  console.log(err)
})
```

 如果 `onRejected` 不是函数且 `promise1` 状态为失败`（Rejected）`，`promise2`必须变为失败`（Rejected）` 并返回 `promise1` 失败的值，例如：

```js
let promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('fail')
  }, 1000)
})
promise2 = promise1.then(res => res, '这里的onRejected本来是一个函数，但现在不是')
promise2.then(res => {
  console.log(res)
}, err => {
  console.log(err)  // 1秒后打印出：fail
})
```

我们需要完善下我们的then方法,首先使用数组存储我们的`onFulfilled`和`onRejected`两个回调函数，因为可能存在多个`onFulfilled`和`onRejected`：

```js
// constructor构造函数中添加
constructor(executor) {
    if (!isFunction(executor)) {
      return new Error("大兄弟，传入的不是函数！！")
    }

    this._state = PENDING; // 初始状态
    this._value = null; //成功返回的值
    this._reason = null; //失败返回的原因，
    this._onFulfilledCallbacks = []  // 存储链式调用时成功的函数
    this._onRejectedCallbacks = []  // 存储链式调用失败的函数

    try {
      // 构造函数执行完成，立即执行executor函数(注意，需要使用bind绑定this的上下文)
      executor(this._resolve.bind(this), this._reject.bind(this))
    } catch (err) {
      this._reject(err)
    }
}
```

重新定义`then`方法

```js
MyPromise.prototype.then = function(onFulfilled, onRejected) {
    const {_state, _value} = this;
    
    return new MyPromise((onFulfilledNext, onRejectedNext) => {
        // 根据then方法的传值策略和捕获异常的规范，定义handleFulfilled和handleRejected函数
        let handleFulfilled = _value => {
            try {
                if (!isFunction(onFulfilled)) {
                    onFulfilledNext(_value)
                } else {
                    let res = onFulfilled(_value);
                    if (res instanceof MyPromise) {
                        // 如果当前回调函数返回的是promise对象，需要等待其执行完毕，再进行下一次回调
                        res.then(onFulfilledNext, onRejectedNext)
                    } else {
                        // 否则，将结果传递给下一次回调函数
                        onFulfilledNext(res)
                    }
                }
            } catch (err) {
                onRejectedNext(err)
            }
        }

        let handleRejected = error => {
            try {
                if (!isFunction(onRejected)) {
                    onRejectedNext(error)
                } else {
                    let res = onRejected(error);
                    if (res instanceof MyPromise) {
                        // 如果当前回调函数返回的是promise对象，需要等待其执行完毕，再进行下一次回调
                        res.then(onFulfilledNext, onRejectedNext)
                    } else {
                        // 否则，将结果传递给下一次回调函数
                        onFulfilledNext(res)
                    }
                }
            } catch (err) {
                onRejectedNext(err)
            }
        }

        switch (_state) {
            case FULFILLED:
                onFulfilled(_value)
                break;
            case REJECTED:
                onRejected(_value)
                break;
            case PENDING:
                this._onFulfilledCallbacks.push(handleFulfilled)
                this._onRejectedCallbacks.push(handleRejected)
                break;
        }
    })
} 
```

这里总算是对值的传递和错误的处理做了规范化，并且收集好了`handleFulfilled`和`handleRejected`，接着我们需要依次取出数组中的函数并执行：

```js
// resolve函数
    _resolve (val) {
        if (this._state !== PENDING) return;
        // 依次取出数组中的函数执行并清空数组
        const run = () => {
            this._state = FULFILLED;
            this._value = val;
            let cb;

            while(this._onFulfilledCallbacks.shift()) {
                cb(val)
            }
        }
        // 为了支持同步的promise,这里异步调用
        setTimeout(() => run(), 0)
    }

    //  reject函数
    _reject (err) {
        if (this._state !== PENDING) return;

        const run = () => {
            this._state = REJECTED;
            this._value = err;

            let cb;

            while(this._onRejectedCallbacks.shift()) {
                cb(err)
            }
        }

        setTimeout(() => run(), 0)
       
    }
```

最后增加一些实例方法和静态方法：

```js
 // 添加catch方法
    catch (onRejected) {
        return this.then(undefined, onRejected)
    }
    
    // 添加resolve方法
    static resolve (value) {
        if (value instanceof MyPromise) return value;
        return new MyPromise(resolve => resolve(value))
    }

    // 添加静态reject方法
    static reject (value) {
        return new MyPromise((resolve, reject) => reject(value))
    }
```

### promise的完整实现

```js
// 实现简单的promise

// 定义一个函数：判断传入的变量是否是函数
const isFunction = variable => typeof variable === 'function';

// 定义Promise的三种状态: pending、fulfilled、rejected

const PENDING = 'pending'
const FULFILLED = 'fulfilled'
const REJECTED = 'rejected'

// 定义一个自己的Promise类
class MyPromise {
    constructor(executor) {
        if (!isFunction(executor)) {
            return new Error("大兄弟，传入的不是函数！！")
        }

        this._state = PENDING;
        this._value = null; //成功返回的值
        this._onFulfilledCallbacks = [] // 存储链式调用时成功的函数
        this._onRejectedCallbacks = [] // 存储链式调用失败的函数

        try {
            executor(this._resolve.bind(this), this._reject.bind(this))
        } catch (err) {
           this._reject(err)
        }
    }

    // executor的第一个参数 resolve方法
    _resolve (val) {
        if (this._state !== PENDING) return;
        // 依次取出数组中的函数执行并清空数组
        const run = () => {
            this._state = FULFILLED;
            this._value = val;
            let cb;

            while(cb = this._onFulfilledCallbacks.shift()) {
                cb(val)
            }
        }
        // 为了支持同步的promise,这里异步调用
        setTimeout(() => run(), 0)
    }

    //  executor的第二个参数 reject方法
    _reject (err) {
        if (this._state !== PENDING) return;

        const run = () => {
            this._state = REJECTED;
            this._value = err;

            let cb;

            while(cb = this._onRejectedCallbacks.shift()) {
                cb(err)
            }
        }

        setTimeout(() => run(), 0)
       
    }

    // 实现then方法
    then (onFulfilled, onRejected) {
        const {_state, _value} = this;
    
        return new MyPromise((onFulfilledNext, onRejectedNext) => {
            // 根据then方法的传值策略和捕获异常的规范，定义handleFulfilled和handleRejected函数
            let handleFulfilled = _value => {
                try {
                    if (!isFunction(onFulfilled)) {
                        onFulfilledNext(_value)
                    } else {
                        let res = onFulfilled(_value);
                        if (res instanceof MyPromise) {
                            // 如果当前回调函数返回的是promise对象，需要等待其执行完毕，再进行下一次回调
                            res.then(onFulfilledNext, onRejectedNext)
                        } else {
                            // 否则，将结果传递给下一次回调函数
                            onFulfilledNext(res)
                        }
                    }
                } catch (err) {
                    onRejectedNext(err)
                }
            }

            let handleRejected = error => {
                try {
                    if (!isFunction(onRejected)) {
                        onRejectedNext(error)
                    } else {
                        let res = onRejected(error);
                        if (res instanceof MyPromise) {
                            // 如果当前回调函数返回的是promise对象，需要等待其执行完毕，再进行下一次回调
                            res.then(onFulfilledNext, onRejectedNext)
                        } else {
                            // 否则，将结果传递给下一次回调函数
                            onFulfilledNext(res)
                        }
                    }
                } catch (err) {
                    onRejectedNext(err)
                }
            }

            switch (_state) {
                case FULFILLED:
                    onFulfilled(_value)
                    break;
                case REJECTED:
                    onRejected(_value)
                    break;
                case PENDING:
                    this._onFulfilledCallbacks.push(handleFulfilled)
                    this._onRejectedCallbacks.push(handleRejected)
                    break;
            }
        })
    }

    // 添加catch方法
    catch (onRejected) {
        return this.then(undefined, onRejected)
    }
    
    // 添加resolve方法
    static resolve (value) {
        if (value instanceof MyPromise) return value;
        return new MyPromise(resolve => resolve(value))
    }

    // 添加静态reject方法
    static reject (value) {
        return new MyPromise((resolve, reject) => reject(value))
    }
}
```

### promisify 

>  promisify 是指将具有异步操作的行为promise化，因为promise确实很适合干这个

如下面这个例子：

```js
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () => callback(null, script);
  script.onerror = () => callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}

// 用法：
// loadScript('path/script.js', (err, script) => {...})
```

为了可读性，我们可以将`loadScript promise化`：

```js
let loadPromise = function (src) {
  return new Promise((resolve, reject) => {
    loadScript(src, (err,script) => {
      if (err) reject(err);
      else resolve(script)
    })
  })
}
```
